title: "Shajan Jacob"
description: "Software engineer from kochi, working as NodeJS developer at Cubet Techno Labs."
avatar: "http://shajanjacob.com/shajan-jacob.jpg"
banner: "https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/d560e7d7d695293217875d2db6fbb35b31fc1991_2880x1620.jpg?w=1200"


social:
  email: shajan@gmail.com
  facebook: shajanjp 
  github: shajanjp 
  instagram: shajanjp 
  linkedin: shajanjp 
  pinterest: shajanjp 
  skype: shajanjp 
  twitter: shajanjp 
  youtube: shajanjp 
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  googleplus: # anything in your profile username that comes after plus.google.com/