title: "Linus Torvalds"
description: " Finnish-American software engineer who is the creator, and for a long time, principal developer of the Linux kernel."
avatar: "http://shajanjacob.com/shajan-jacob.jpg"