title: "Shajan Jacob"
description: "Shajan Jacob is an Indian Computer Science Engineer and a passionate web developer who is the founder of GuysWhoCode."
avatar: "http://shajanjacob.com/shajan-jacob.jpg"