title: "Linus Torvalds"
description: " Finnish-American software engineer who is the creator, and for a long time, principal developer of the Linux kernel."
avatar: "http://shajanjacob.com/shajan-jacob.jpg"
banner: "https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/d560e7d7d695293217875d2db6fbb35b31fc1991_2880x1620.jpg?w=1200"


social:
  email: linus@gmail.com
  facebook: linus 
  github: linus 
  instagram: linus 
  linkedin: linus 
  pinterest: linus 
  skype: linus 
  twitter: linus 
  youtube: linus 
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  googleplus: # anything in your profile username that comes after plus.google.com/